settings:
  number_of_shards: 1
  number_of_replicas: 1
  refresh_interval: "1s"

mappings:
  properties:
    id:
      type: keyword
    title:
      type: text
    content:
      type: text
    topics:
      type: nested # Correct the topics mapping to nested
      properties:
        name:
          type: keyword
        score:
          type: float
    created_utc:
      type: date
    author:
      type: keyword
    subreddit:
      type: keyword
